DROP TABLE IF EXISTS VENDAS;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS VIAGEM;
DROP TABLE IF EXISTS CARTAO_CREDITO;

CREATE TABLE USUARIO(
ID_USUARIO BIGSERIAL PRIMARY KEY NOT NULL,
NOME TEXT NOT NULL,
EMAIL TEXT NOT NULL,
SENHA TEXT NOT NULL);

CREATE TABLE VIAGEM(
ID_VIAGEM BIGSERIAL PRIMARY KEY NOT NULL,
NOME TEXT,
CIDADE TEXT,
FOTO BYTEA,
DESCRICAO TEXT,
VALOR DECIMAL,
DT_SAIDA TIMESTAMP,
QUANTIDADE INTEGER
);

CREATE TABLE CARTAO_CREDITO(
ID_CARTAO_CREDITO BIGSERIAL PRIMARY KEY NOT NULL,
NUM_CARTAO INTEGER,
TITULAR_CARTAO TEXT,
DT_VALIDADE DATE,
COD_SEGURANCA INTEGER
);

CREATE TABLE VENDAS (
ID_VENDAS BIGSERIAL PRIMARY KEY NOT NULL,
QUANTIDADE INTEGER,
CHECKIN TIMESTAMP,
CPF TEXT,
TELEFONE TEXT,
DT_COMPRA TIMESTAMP,
FK_USUARIO INTEGER,
FK_VIAGEM INTEGER,
FK_CARTAO_CREDITO INTEGER
);

ALTER TABLE VENDAS ADD FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO(ID_USUARIO);
ALTER TABLE VENDAS ADD FOREIGN KEY (FK_VIAGEM) REFERENCES VIAGEM(ID_VIAGEM);
ALTER TABLE VENDAS ADD FOREIGN KEY (FK_CARTAO_CREDITO) REFERENCES CARTAO_CREDITO(ID_CARTAO_CREDITO);



INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA) VALUES (1, 'admin', 'admin@gmail.com', '123');